
pipeline_name: dp_pusht
# env
env_name: pusht-v0
abs_action: false
dataset_path: dev/pusht/pusht_cchi_v7_replay.zarr
mode: train
max_episode_steps: 300
obs_keys: ["state", "action"]
obs_dim: 5
action_dim: 2
obs_steps: 2
action_steps: 8
# train
device: cuda:0
seed: 0
gradient_steps: 1000000
batch_size: 256
horizon: 10
nn: dit
diffusion: ddpm
sample_steps: 5
# optimizer
lr: 0.0001
# eval
model_path: path/to/model
eval_episodes: 50
num_envs: 1
eval_freq: 100000
save_video: true
# log
exp_name: ${env_name}_abs_${abs_action}_${nn}_${diffusion}_sample_${sample_steps}_horizon_${horizon}
save_path: logs
project: CleanDiffuser
group: dp_pusht
wandb_mode: offline
log_freq: 1000
save_freq: 100000
work_dir: ${save_path}/${pipeline_name}/${mode}/${env_name}/${exp_name}_${now:%Y%m%d_%H%M%S}/${seed}
# hydra
hydra:
  run:
    dir: ${work_dir}
  job:
    chdir: false
